FROM registry.svc.ci.openshift.org/openshift/release:golang-1.13 AS builder

ADD . /go/src/openshift/node-feature-discovery

WORKDIR /go/src/openshift/node-feature-discovery


RUN go install \
  -ldflags "-X openshift/node-feature-discovery/pkg/version.version=v0.6.0" \
  ./cmd/*
RUN install -D -m644 nfd-worker.conf.example /etc/kubernetes/node-feature-discovery/nfd-worker.conf

RUN make test

FROM registry.svc.ci.openshift.org/openshift/origin-v4.0:base

# Use more verbose logging of gRPC
ENV GRPC_GO_LOG_SEVERITY_LEVEL="INFO"

COPY --from=builder /etc/kubernetes/node-feature-discovery /etc/kubernetes/node-feature-discovery
COPY --from=builder /go/bin/nfd-* /usr/bin/
